name: Run Ryanair Scraper

on:
  schedule:
    # Run every day at 10:00 UTC
    - cron: "0 10 * * *"
    # Run every day at 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:  # allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install Google Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller

    # Step 5: Run the Python scraper script
    - name: Run scraper
      run: |
        python main.py

    # Step 6: Commit and push updates
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "github-actions"
        author_email: "github-actions@github.com"
        message: "Update Ryanair scrape data"
        add: "ryanair_countdown.csv logs/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
