name: Run Page Checker

on:
  schedule:
     Runs every 20 minutess
     - cron: '*/5 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Python scraper script
    - name: Run scraper
      run: |
        python main.py

    # Step 5: Commit and push updates
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
        message: 'Update visit log'
        add: 'visit_log.txt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
